name: Display Name Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2



        
      - name: Echo Name
        run: echo "Hi,Mahammad Anis Vahora"
